# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.CharField(default='', max_length=64),
        ),
    ]
